name: build mpt4py wheels

on:
  workflow_dispatch:

jobs:
  build_wheel:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
        with:
          repository: PREDICT-EPFL/mpt4py
          ref: 0.1.3
          token: ${{ secrets.MPT4PY_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install 3.12

      - name: Build wheel
        run: uv build --wheel

      - name: Release current commit
        uses: ncipollo/release-action@v1.18.0
        with:
          artifacts: "dist/*.whl"
          tag: "mpt4py_wheels"
          name: "mpt4py_wheels"
          removeArtifacts: false
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: false
