name: lock requirements

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  lock_requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Lock requirements
        run: uv pip compile requirements.txt -o locked-requirements.txt --emit-find-links --universal --python-version 3.12

      - name: Check for changes
        id: git-check
        run: |
          if git diff --quiet locked-requirements.txt; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add locked-requirements.txt
          git commit -m "lock requirements"
          git push
